#intitialize the screen

_FEET2INCHES = 12
_MULTIPLIER = 5
_DISPLAY_WIDTH = _DISPLAY_HEIGHT = 8 * _FEET2INCHES * _MULTIPLIER
_BLOCK_OFFSET = _OBSTACLE_OFFSET = 1.5 * _MULTIPLIER
_MS_OFFSET = 3 * _MULTIPLIER
_EDGE_OFFSET = _SPACING_OFFSET = 6 * _MULTIPLIER
_STARTX = _STARTY = 4 * _FEET2INCHES * _MULTIPLIER
_SIM_SPEED = int(500/10) #change denominator to adjust sim speed
